# Generated by Django 4.2.6 on 2023-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_club_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(choices=[('Event management', 'Event management'), ('Graphic Design', 'Graphic Design'), ('Finance', 'Finance'), ('Quant', 'Quant'), ('Probability Statistics', 'Probability Statistics'), ('Mechanical', 'Mechanical'), ('CAD-CAM', 'CAD-CAM'), ('Script writing', 'Script writing'), ('Directoring', 'Directoring'), ('casting', 'casting'), ('Costume Design', 'Costume Design'), ('Direction', 'Direction'), ('Chess', 'Chess'), ('Debating', 'Debating'), ('Communication', 'Communication'), ('Politics', 'Politics'), ('Content Writing', 'Content Writing'), ('Film making', 'Film making'), ('Video editing', 'Video editing'), ('Videography', 'Videography'), ('Motion Design', 'Motion Design'), ('UI/UX Design', 'UI/UX Design'), ('Field work', 'Field work'), ('Team management', 'Team management'), ('Blockchain Development', 'Blockchain Development'), ('Leadership', 'Leadership'), ('Dance', 'Dance'), ('Choreography', 'Choreography'), ('Photography', 'Photography'), ('ML', 'ML'), ('Aerodynamics', 'Aerodynamics'), ('Data Science', 'Data Science'), ('Quantum Computing', 'Quantum Computing'), ('Electronics', 'Electronics'), ('Hardware Engineering', 'Hardware Engineering'), ('Web Development', 'Web Development'), ('Podcasting', 'Podcasting'), ('RJ', 'RJ'), ('Physics and Astronomy', 'Physics and Astronomy'), ('Audio', 'Audio'), ('Soft skills', 'Soft skills'), ('Social media', 'Social media'), ('Robotics', 'Robotics'), ('Drones', 'Drones'), ('AR/VR', 'AR/VR'), ('Wellness', 'Wellness'), ('Sanskrit', 'Sanskrit'), ('Music', 'Music'), ('Musical Instruments', 'Musical Instruments'), ('Automotives', 'Automotives'), ('Marketing', 'Marketing'), ('Mobile Development', 'Mobile Development'), ('Mentorship', 'Mentorship'), ('Game Development', 'Game Development'), ('Trekking', 'Trekking'), ('Range Rovering', 'Range Rovering'), ('Skating', 'Skating'), ('Information Security', 'Information Security'), ('Mountaineering', 'Mountaineering'), ('Competitive Programming', 'Competitive Programming'), ('DSA', 'DSA'), ('CTF', 'CTF'), ('Maths', 'Maths'), ('Music production', 'Music production'), ('DJ', 'DJ'), ('Fashion modelling', 'Fashion modelling'), ('Stock market', 'Stock market'), ('Consultancy', 'Consultancy'), ('Product management', 'Product management'), ('Analytics', 'Analytics'), ('Formula one', 'Formula one'), ('Business administration', 'Business administration')], max_length=255),
        ),
    ]
